# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e1797ccec2aa96ce2c0472363cea1982a0edb0e30622facf4c5aa40579c9c15d92b5888885e907f9ba105577d69aab031d3348a89f7919245d730a94be3044

test:
  secret_key_base: 1b6a69e95897d8a5235db60f9df64dda0a35b40edebe560998a67145e5496507ad800510b88dfe7e16e737694d1515bc6558bd548dbea2126a41a5ecd5fefd1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
